appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a987b5930700c339fd
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: dNkKDRl7VatCuYB0YMNdHSDlJRv4vt7DXAeCEKSfMUqZ/2jJCXe5r9nL2htcbur4LT98miLsCKjVXctE88XksftYozqcXghO/upEN1OtgCbPBkTcmjleTw3sW6zu7Bri+EIYgQ1wzLA606xEqAZNSrcayjDgNfRMingHoNgOpd7czLl4euRgtB7ls0s+qqTWs1lKRIelNQHgle/pk1c9ulHUiHk4NkXl8DoKVEPCRrrUSgAxhjvRYxu818q3edAPDMnQCQ+WUBg3noZYPsRLiUIRmcrFxX6Ds1yVfLRlF2M4vIx2OKeLng3OQyVHMcpcFIoXenhL3Unydr/MT5Ss0OtyV6Gm0/C2C304XjwpqE7ueC0UPEflWOpO8YE774gw+gPkzKncRPoDaxHL10lSK0RAZcu50CnkLC+HZxeBkAV8FcYpyGK38wgTpZK+xc1YELsUvrCBOBh7M2D6VuO1VpG4oIEJJhTfngzWoCsor9qvejZWib+9eI0aeEC6wmCbCCZdHTdEFvLnvQ6dhhjrKMozrt6nXr6/k3q44NunKd+sK8sSaEe2h+6tTXJck0l1DsQfmjKK5qWEASVsdNxx6tmDwM/EJJuukrQIlbcLGOuGiNuKNyhsUME5skITMnN6dyqk7eSIMYZyZVm1v2X25lzluPQUqO2ojLQnsZY9aOw=}
